feat: allow path encoding to be disabled
imgix/react-imgix pull request #849
Opened 2022-02-24 18:58 UTC by frederickfogerty

This PR exposes the feature to disable path encoding, that was recently added to js-core. This behaviour is exposed through a new `disablePathEncoding` prop. Information about this new prop can be found in the README. 

Closes #815

2022-02-24 18:58 UTC, frederickfogerty commented
Current dependencies on/for this PR:
* main
  * **PR #849** <a href="https://app.graphite.dev/github/pr/imgix/react-imgix/849" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-24 20:06 UTC, sherwinski requested changes
Tracking some follow-up items before I forget:
1. We need to update js-core to enable the disable encoding feature
2. As per [this comment](https://github.com/imgix/react-imgix/issues/815#issuecomment-1050181249) we should investigate if this works with the provider component

2022-02-25 10:54 UTC, frederickfogerty reviewed
@sherwinski I believe I've handled both of those concerns

2022-02-25 20:35 UTC, sherwinski approved these changes
LGTM

2022-02-28 12:04 UTC, merged